### ISSUE TITLE
Slogan per Default aus?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/blue-edgy#2]
Ist der Slogan sichtbar? Für Suchmaschinen schon. Aber die User sehen den nicht, oder? Denn sonst würden die doch "Ein weiterer RRZE CMS-Dienst Blog " ersetzen...?

**Comment by endv02** [comment]
Auch die Administratoren der Seite sehen in den Einstellungen normalerweise den Untertitel und können den ändern. Hängt nicht am Theme, Rolf schaut sich das mal in der API an.
