### ISSUE TITLE
Shortcode für Accordions einbauen

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/blue-edgy#6]
Gewünscht ist der Einbau des Shortcode collabsibles identisch zu den Fakultäts-Themes.

**Comment by cassandre** [comment]
Falls es jemand braucht: Im Theme Luna habe ich es eingebaut, kann rauskopiert werden:
https://github.com/RRZE-Webteam/Design-Luna/blob/master/functions.php#L1244, Z. 1244-1271 
Der Text für den Hilfe-Tab ist [Z. 1587-1605](https://github.com/RRZE-Webteam/Design-Luna/blob/master/functions.php#L1587).
Ich weiß allerdings nicht, ob die Parameter exakt identisch sind (title und color). Und das CSS müsste wahrscheinlich angepasst werden: https://github.com/RRZE-Webteam/Design-Luna/blob/master/css/layout.css#L1645

**Comment by endv02** [comment]
ist eindimensional drin, nicht geschachtelt
